// Exporter module: Direct PDF generation, Markdown, Anki/JSON, Print-to-PDF, and Multi-channel sharing
import { PDFGenerator } from './pdf-generator.js';

export class Exporter {
  /**
   * Direct 1-Click Download of AI-Generated Revision Notes PDF
   */
  static downloadNotesPDF(data) {
    const doc = PDFGenerator.generateNotesPDF(data);
    const safeTitle = (data.metadata?.title || "Lecture").replace(/[^a-zA-Z0-9_-]/g, "_");
    PDFGenerator.savePDF(doc, `${safeTitle}_Revision_Notes.pdf`);
    return doc;
  }

  /**
   * Direct 1-Click Download of 5-Question Practice Quiz PDF
   */
  static downloadQuizPDF(data) {
    const doc = PDFGenerator.generateQuizPDF(data);
    const safeTitle = (data.metadata?.title || "Lecture").replace(/[^a-zA-Z0-9_-]/g, "_");
    PDFGenerator.savePDF(doc, `${safeTitle}_Practice_Quiz.pdf`);
    return doc;
  }

  /**
   * Direct 1-Click Download of Complete Study Pack PDF (Notes + Quiz)
   */
  static downloadCompletePackPDF(data) {
    const doc = PDFGenerator.generateCompletePackPDF(data);
    const safeTitle = (data.metadata?.title || "Lecture").replace(/[^a-zA-Z0-9_-]/g, "_");
    PDFGenerator.savePDF(doc, `${safeTitle}_Complete_Study_Pack.pdf`);
    return doc;
  }

  /**
   * Generate clean Markdown string
   */
  static generateMarkdown(data) {
    const { metadata = {}, notes = {}, quiz = [] } = data;
    const title = metadata.title || "Lecture Revision";

    let md = `# ${title}\n`;
    md += `*Generated by StudyPulse AI | Subject: ${metadata.subject?.toUpperCase() || "GENERAL"} | Style: ${metadata.style || "Standard"}*\n`;
    md += `*Date: ${metadata.generatedAt || new Date().toLocaleDateString()} | Word Count: ${metadata.wordCount || 0}*\n\n`;

    const quickSummary = notes.quickSummary || notes.execSummary;
    if (quickSummary) {
      md += `## 📋 Quick Summary\n\n${quickSummary}\n\n`;
    }

    const concepts = notes.importantConcepts || [];
    if (concepts.length > 0) {
      md += `## 💡 Important Concepts\n\n`;
      concepts.forEach(c => {
        md += `- **${c.concept}**: ${c.explanation}\n`;
      });
      md += `\n`;
    }

    const defs = notes.keyDefinitions || notes.terms || [];
    if (defs.length > 0) {
      md += `## 🔑 Key Definitions\n\n`;
      defs.forEach(t => {
        md += `### ${t.term} [${t.importance || 'KEY TERM'}]\n`;
        md += `- **Definition**: ${t.definition}\n`;
        if (t.tip) md += `- **Exam Tip**: ${t.tip}\n`;
        md += `\n`;
      });
    }

    md += `## 📐 Important Formulas\n\n`;
    if (notes.importantFormulas && notes.importantFormulas.length > 0) {
      notes.importantFormulas.forEach(f => {
        md += `### ${f.name}\n`;
        md += `\`\`\`\n${f.formula}\n\`\`\`\n`;
        md += `- **Application**: ${f.explanation}\n\n`;
      });
    } else {
      md += `No important formulas found.\n\n`;
    }

    const examTips = notes.examTips || (notes.pitfalls ? notes.pitfalls.map(p => `Watch out: ${p.trap} — remember that ${p.fix}`) : []);
    if (examTips.length > 0) {
      md += `## 🎯 Exam Tips\n\n`;
      examTips.forEach(tip => {
        md += `- ⚡ ${tip}\n`;
      });
      md += `\n`;
    }

    const takeaways = notes.keyTakeaways || notes.cheatSheet || [];
    if (takeaways.length > 0) {
      md += `## 🚀 Key Takeaways\n\n`;
      takeaways.forEach((k, idx) => {
        md += `${idx + 1}. ${k}\n`;
      });
      md += `\n---\n\n`;
    }

    if (quiz && quiz.length > 0) {
      md += `## 🎯 5-Question Practice Quiz & Diagnostic Rationales\n\n`;
      quiz.forEach((q, idx) => {
        md += `### Question ${idx + 1}: ${q.question}\n`;
        q.options.forEach((opt, oIdx) => {
          const isCorrect = oIdx === q.correctIndex;
          md += `- [${isCorrect ? 'x' : ' '}] ${String.fromCharCode(65 + oIdx)}) ${opt}\n`;
        });
        md += `\n**Correct Answer**: Option ${String.fromCharCode(65 + q.correctIndex)}\n`;
        md += `**Explanation**: ${q.explanation}\n`;
        md += `**Citation**: ${q.citation}\n\n`;
      });
    }

    return md;
  }

  /**
   * Export the entire revision suite as clean Markdown (.md)
   */
  static exportMarkdown(data) {
    const md = this.generateMarkdown(data);
    const safeTitle = (data.metadata?.title || "Lecture_Revision").replace(/[^a-zA-Z0-9_-]/g, "_");
    this.downloadFile(md, `${safeTitle}_Revision_Suite.md`, 'text/markdown');
    return md;
  }

  /**
   * Generate Anki-ready flashcard JSON object or string
   */
  static generateAnkiJSON(data) {
    const { metadata = {}, notes = {}, quiz = [] } = data;
    const cards = [];

    // Definition cards
    const defs = notes.keyDefinitions || notes.terms || [];
    defs.forEach(t => {
      cards.push({
        deck: `${metadata.title || 'Lecture'} - Key Definitions`,
        front: `<strong>${t.term}</strong><br><small>(${metadata.subject || 'General'})</small>`,
        back: `${t.definition}${t.tip ? `<br><br><em>Exam Tip:</em> ${t.tip}` : ''}`,
        tags: ["StudyPulse", "Definition", metadata.subject || 'General']
      });
    });

    // Formula cards
    (notes.importantFormulas || []).forEach(f => {
      cards.push({
        deck: `${metadata.title || 'Lecture'} - Formulas`,
        front: `📐 <strong>Formula:</strong> ${f.name}`,
        back: `<code>${f.formula}</code><br><br>${f.explanation}`,
        tags: ["StudyPulse", "Formula"]
      });
    });

    // Exam Tip cards
    const tips = notes.examTips || [];
    tips.forEach((tip, idx) => {
      cards.push({
        deck: `${metadata.title || 'Lecture'} - Exam Tips`,
        front: `🎯 <strong>Exam Tip #${idx + 1}</strong>`,
        back: `${tip}`,
        tags: ["StudyPulse", "ExamTip"]
      });
    });

    // Quiz cards
    (quiz || []).forEach((q, idx) => {
      const optionsText = q.options.map((opt, i) => `${String.fromCharCode(65 + i)}) ${opt}`).join("<br>");
      cards.push({
        deck: `${metadata.title || 'Lecture'} - Quiz`,
        front: `<strong>Q${idx + 1}:</strong> ${q.question}<br><br>${optionsText}`,
        back: `<strong>Correct: ${String.fromCharCode(65 + q.correctIndex)}) ${q.options[q.correctIndex]}</strong><br><br>${q.explanation}`,
        tags: ["StudyPulse", "Quiz"]
      });
    });

    return JSON.stringify({
      title: metadata.title || 'Lecture',
      exportedAt: new Date().toISOString(),
      cardCount: cards.length,
      cards
    }, null, 2);
  }

  /**
   * Export as Anki-ready flashcard JSON
   */
  static exportAnkiJSON(data) {
    const jsonStr = this.generateAnkiJSON(data);
    const safeTitle = (data.metadata?.title || "Lecture").replace(/[^a-zA-Z0-9_-]/g, "_");
    this.downloadFile(jsonStr, `${safeTitle}_Flashcards.json`, 'application/json');
    return jsonStr;
  }

  /**
   * Trigger print dialog formatted specifically via print.css
   */
  static triggerPrintPDF() {
    window.print();
  }

  /**
   * Generate nicely formatted sharing text for Notes, Quiz, or Complete Pack
   */
  static getShareText(data, type = 'notes') {
    const { metadata = {}, notes = {}, quiz = [] } = data;
    const title = metadata.title || "Lecture Study Pack";

    if (type === 'quiz') {
      let text = `🎯 Practice Quiz: ${title}\n`;
      text += `Subject: ${metadata.subject?.toUpperCase() || 'General'} | ${quiz.length} Questions\n\n`;
      quiz.forEach((q, i) => {
        text += `Q${i + 1}: ${q.question}\n`;
        q.options.forEach((opt, oI) => {
          text += `  ${String.fromCharCode(65 + oI)}) ${opt}\n`;
        });
        text += `\n`;
      });
      text += `Generated by StudyPulse AI • Fast, Focused & Distraction-Free\n`;
      return text;
    }

    if (type === 'pack') {
      let text = `📚 Complete Study Pack: ${title}\n\n`;
      const sum = notes.quickSummary || notes.execSummary;
      if (sum) text += `📋 QUICK SUMMARY:\n${sum}\n\n`;
      
      const concepts = notes.importantConcepts || [];
      if (concepts.length) {
        text += `💡 KEY CONCEPTS:\n` + concepts.map(c => `• ${c.concept}: ${c.explanation}`).join('\n') + `\n\n`;
      }
      
      const takeaways = notes.keyTakeaways || [];
      if (takeaways.length) {
        text += `🚀 KEY TAKEAWAYS:\n` + takeaways.map((t, i) => `${i + 1}. ${t}`).join('\n') + `\n\n`;
      }

      text += `🎯 PRACTICE QUIZ (${quiz.length} Questions included in PDF export)\n\n`;
      text += `Generated by StudyPulse AI\n`;
      return text;
    }

    // Default: Revision notes text
    let text = `📚 Revision Notes: ${title}\n\n`;
    const sum = notes.quickSummary || notes.execSummary;
    if (sum) text += `📋 QUICK SUMMARY:\n${sum}\n\n`;

    const concepts = notes.importantConcepts || [];
    if (concepts.length) {
      text += `💡 IMPORTANT CONCEPTS:\n` + concepts.map(c => `• ${c.concept}: ${c.explanation}`).join('\n') + `\n\n`;
    }

    const defs = notes.keyDefinitions || notes.terms || [];
    if (defs.length) {
      text += `🔑 KEY DEFINITIONS:\n` + defs.map(d => `• ${d.term}: ${d.definition}`).join('\n') + `\n\n`;
    }

    if (notes.importantFormulas && notes.importantFormulas.length) {
      text += `📐 IMPORTANT FORMULAS:\n` + notes.importantFormulas.map(f => `• ${f.name}: ${f.formula}`).join('\n') + `\n\n`;
    }

    const tips = notes.examTips || [];
    if (tips.length) {
      text += `🎯 EXAM TIPS:\n` + tips.map(t => `• ${t}`).join('\n') + `\n\n`;
    }

    const takeaways = notes.keyTakeaways || [];
    if (takeaways.length) {
      text += `🚀 KEY TAKEAWAYS:\n` + takeaways.map((k, i) => `${i + 1}. ${k}`).join('\n') + `\n\n`;
    }

    text += `Generated with StudyPulse AI\n`;
    return text;
  }

  /**
   * Multi-channel sharing engine (Native Share API with PDF file, WhatsApp, Email, Clipboard)
   */
  static async shareContent({ data, type = 'notes', method = 'native' }) {
    const safeTitle = (data.metadata?.title || "Lecture").replace(/[^a-zA-Z0-9_-]/g, "_");
    const shareText = this.getShareText(data, type);
    const subject = `StudyPulse: ${data.metadata?.title || 'Lecture Study Pack'} (${type.toUpperCase()})`;

    // 1. WhatsApp share
    if (method === 'whatsapp') {
      const url = `https://api.whatsapp.com/send?text=${encodeURIComponent(shareText)}`;
      window.open(url, '_blank');
      return { success: true, method: 'whatsapp' };
    }

    // 2. Email share
    if (method === 'email') {
      const mailto = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(shareText)}`;
      window.location.href = mailto;
      return { success: true, method: 'email' };
    }

    // 3. Clipboard copy
    if (method === 'clipboard') {
      const ok = await this.copyTextToClipboard(shareText);
      return { success: ok, method: 'clipboard' };
    }

    // 4. Native Web Share (with PDF file if supported)
    if (typeof navigator !== 'undefined' && navigator.share) {
      try {
        let doc, filename;
        if (type === 'quiz') {
          doc = PDFGenerator.generateQuizPDF(data);
          filename = `${safeTitle}_Practice_Quiz.pdf`;
        } else if (type === 'pack') {
          doc = PDFGenerator.generateCompletePackPDF(data);
          filename = `${safeTitle}_Complete_Study_Pack.pdf`;
        } else {
          doc = PDFGenerator.generateNotesPDF(data);
          filename = `${safeTitle}_Revision_Notes.pdf`;
        }

        const blob = PDFGenerator.toBlob(doc);
        const file = new File([blob], filename, { type: 'application/pdf' });

        if (navigator.canShare && navigator.canShare({ files: [file] })) {
          await navigator.share({
            title: subject,
            text: `Study notes and practice quiz for "${data.metadata?.title}" synthesized by StudyPulse AI.`,
            files: [file]
          });
          return { success: true, method: 'native-file' };
        } else {
          // Fallback to text sharing
          await navigator.share({
            title: subject,
            text: shareText
          });
          return { success: true, method: 'native-text' };
        }
      } catch (err) {
        if (err.name === 'AbortError') {
          return { success: false, aborted: true };
        }
        console.warn("Native share failed, falling back to clipboard:", err);
      }
    }

    // Default fallback: copy to clipboard
    const ok = await this.copyTextToClipboard(shareText);
    return { success: ok, method: 'clipboard-fallback' };
  }

  /**
   * Helper to copy text to clipboard
   */
  static async copyTextToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (e) {
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      return true;
    }
  }

  /**
   * Copy formatted text summary to clipboard
   */
  static async copyToClipboard(data) {
    const text = this.getShareText(data, 'notes');
    return this.copyTextToClipboard(text);
  }

  /**
   * Browser file download helper
   */
  static downloadFile(content, filename, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 150);
  }
}
